server:
  port: 8081

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: ${user.home}/info-ins/logs/admin-service.log

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://mysql-server:3306/INFOINS?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

module: Admin

jasper:
  reports:
    resource:
      path: ${user.home}/info-ins/resource/reports/
      class:
        path: ${user.home}/info-ins/resource/

message:
  default:
    welcome: Welcome...Default